version: 2
project_name: lspath

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X lspath/internal/model.Version={{.Version}}
    main: ./main.go

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    # This logic removes the 'v1' and fixes 'x86_64' vs 'amd64'
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_
      {{- if eq .Arch "amd64" -}}x86_64
      {{- else if and (eq .Os "darwin") (eq .Arch "arm64") -}}arm64
      {{- else if eq .Arch "arm64" -}}aarch64
      {{- else -}}{{ .Arch }}{{- end -}}

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Format "rpm" -}}
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "arm64" }}aarch64
        {{- else }}{{ .Arch }}{{ end -}}
      {{- else -}}
        {{ .Arch }}
      {{- end -}}
    formats:
      - deb
      - rpm
    description: "lspath is a tool for analyzing and debugging your system PATH."
    maintainer: "Andy Bulka <abulka@gmail.com>"
    license: MIT
    homepage: "https://github.com/abulka/lspath"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'